spring:
  application:
    name: galactictournament

  datasource:
    url: ${MAIN_DB_URL}
    username: ${MAIN_DB_USER}
    password: ${MAIN_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver